# Page settings

baseURL = "https://jwelectrical.netlify.app/"
languageCode = "en"
title = "J.W. Electrical"
theme = "hugo-business-frontpage-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "Business Frontpage - A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header"






    [params.navbar]
        name = "Start Bootstrap"
        url = "#"

        [[params.navbar.nav]]
        current = true
        name = "Home"
        url = "#"
        [[params.navbar.nav]]
        name = "About"
        url = "#"
        [[params.navbar.nav]]
        name = "Services"
        url = "#"
        [[params.navbar.nav]]
        name = "Contact"
        url = "#"






    [params.header]
        name = "J.W. Electric"
        tagline = "Providing personal and commercial electrical services to Kingston and the Islands, Ontario."






    [params.summary]
        url = "#"

        [params.summary.description]

        [[params.summary.description.items]]
        description = "I am a certified Master electrician with over ten years experience providing electrical serivces to both personal households and for commercial developments."
        [[params.summary.description.items]]
        description = "I provide reliable and affordable services to people in Kingston and the Islands, with a flexible schedule depending on my clients needs and availability. Please call or email me for more information about my services."


        [params.summary.contact]
        name = "J.W. Electric"
        #address1 = "3481 Melrose Place"
        #address2 = "Beverly Hills, CA 90210"
        phone = "(613) 561-3580"
        email = "joshwylie99@outlook.com"






    [params.projects]

        [[params.projects.sections]]
        title = "My work"

        [[params.projects.sections.rows]]
        # title = "My work"

        [[params.projects.sections.rows.items]]
        title = "Pool"
        description = "Connected new pool to electrical source."
        url = "#"
        image = "project1.jpg"
        [[params.projects.sections.rows.items]]
        title = "Home electrical panel"
        description = "Replacing aged home electrical panels with new hardware."
        url = "#"
        image = "project2.jpg"
        [[params.projects.sections.rows.items]]
        title = "Residential lighting"
        description = "Replace and add new indoor lighting."
        url = "#"
        image = "project3.jpg"

        



    [params.footer]
        copyright = "J.W. Electrical"



