# Page settings

baseURL = "https://jwelectrical.netlify.app/"
languageCode = "en"
title = "J.W. Electrical"
theme = "hugo-business-frontpage-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "Business Frontpage - A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header"






    [params.navbar]
        name = "J.W. Electric"
        url = "#"

        [[params.navbar.nav]]
        #current = true
        #name = "Home"
        #url = "#"
        [[params.navbar.nav]]
        #name = "About"
        #url = "#"
        [[params.navbar.nav]]
        #name = "Services"
        #url = "#"
        [[params.navbar.nav]]
        #name = "Contact"
        #url = "#"






    [params.header]
        name = "J.W. Electric"
        tagline = "Providing personal and commercial electrical services to Kingston and the Islands, Ontario."






    [params.summary]
        url = "www.google.com"

        [params.summary.description]

        [[params.summary.description.items]]
        description = "I am a certified Master electrician with over ten years experience providing electrical services to both personal households and for commercial developments."
        [[params.summary.description.items]]
        description = "I provide reliable and affordable services to people in Kingston and the Islands, with a flexible schedule depending on my clients needs and availability. Please call or email me for more information about my services."


        [params.summary.contact]
        name = "J.W. Electric"
        #address1 = "3481 Melrose Place"
        #address2 = "Beverly Hills, CA 90210"
        phone = "(613) 561-3580"
        email = "joshwylie99@outlook.com"






    [params.projects]

        [[params.projects.sections]]
        #title = "My work"

        [[params.projects.sections.rows]]
        title = "Testimonials"

        [[params.projects.sections.rows.items]]
        title = "He rocks down to, electric avenue"
        description = "I worked with Josh to install my new pool. He worked quick and provided excellent service."
        #url = "#"
        image = "project1.jpg"
        [[params.projects.sections.rows.items]]
        title = "I see the light"
        description = "Josh was professional and timely, and did excellent work and answered all my questions. Will hire him agian!"
        #url = "#"
        image = "project2.jpg"
        [[params.projects.sections.rows.items]]
        title = "I can see clearly now the light is installed"
        description = "Great work, I will be hiring him for my next renovations"
        #url = "#"
        image = "project3.jpg"

        



    [params.footer]
        copyright = "J.W. Electrical"



